-- MySQL Script generated by MySQL Workbench
-- Thu 04 Feb 2016 23:20:28 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hexhack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hexhack` ;

-- -----------------------------------------------------
-- Schema hexhack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hexhack` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hexhack` ;

-- -----------------------------------------------------
-- Table `hexhack`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hexhack`.`Users` ;

CREATE TABLE IF NOT EXISTS `hexhack`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hexhack`.`Images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hexhack`.`Images` ;

CREATE TABLE IF NOT EXISTS `hexhack`.`Images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hexhack`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hexhack`.`Tags` ;

CREATE TABLE IF NOT EXISTS `hexhack`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hexhack`.`Images_has_Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hexhack`.`Images_has_Tags` ;

CREATE TABLE IF NOT EXISTS `hexhack`.`Images_has_Tags` (
  `Image_id` INT NOT NULL,
  `Tag_id` INT NOT NULL,
  PRIMARY KEY (`Image_id`, `Tag_id`),
  INDEX `fk_Images_has_Tags_Tags1_idx` (`Tag_id` ASC),
  INDEX `fk_Images_has_Tags_Images_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Images_has_Tags_Images`
    FOREIGN KEY (`Image_id`)
    REFERENCES `hexhack`.`Images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Images_has_Tags_Tags1`
    FOREIGN KEY (`Tag_id`)
    REFERENCES `hexhack`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `hexhack`.`Users` (`username`,`password`) values ('user',md5('pass'));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
