const APP_INIT_API_URL = "APP_INIT_API_URL"
const APP_INIT_DATA_FETCH = "APP_INIT_DATA_FETCH"
const APP_LOGIN_REQUEST = "APP_LOGIN_REQUEST"
const APP_LOGOUT_REQUEST = "APP_LOGOUT_REQUEST"


/* canvas thumbnail actions */
const THUMB_TOGGLE_SELECT = "THUMB_TOGGLE_SELECT"
const THUMB_ADD_IMAGE_THUMB = "THUMB_ADD_IMAGE_THUMB"
const THUMB_HIDE_IMAGE_THUMB = "THUMB_HIDE_IMAGE_THUMB"
const THUMB_TRANSLATE = "THUMB_TRANSLATE"

